<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
'ID' => 'Identifikátor',
'Username' => 'Uživatelské jméno',
'Active' => 'Aktivní',
'Are you sure you want to delete this user?' => 'Jste si jisti, že chcete smazat tohoto uživatele?',
'Banned' => 'Zakázán',
'Bind to IP' => 'Přiřadit k IP',
'Browser' => 'Prohlížeč',
'Change own password' => 'Změnit vlastní heslo',
'Change password' => 'Změnit heslo',
'Changing password' => 'Měním heslo',
'Changing password for user: ' => 'Změna hesla pro uživatele: ',
'Child permissions' => 'Dětská oprávnění',
'Child roles' => 'Dětské role',
'Code' => 'Kód',
'Create' => 'Vytvořit',
'Created' => 'Vytvořeno',
'Creating permission group' => 'Vytváření skupiny oprávnění',
'Current password' => 'Aktuální heslo',
'Data' => 'Data',
'Delete' => 'Smazat',
'Description' => 'Popis',
'E-mail confirmed' => 'E-mail potvrzen',
'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => 'E-mail s aktivačním odkazem byl odeslán na <b>{email}</b>. Tento odkaz vyprší za {minutes} min.',
'Edit' => 'Upravit',
'Editing' => 'Úprava',
'Editing permission group' => 'Úprava skupiny oprávnění',
'Editing permission: ' => 'Úprava oprávnění: ',
'Editing role: ' => 'Úprava role: ',
'Editing user: ' => 'Úprava uživatele: ',
'For example: 123.34.56.78, 168.111.192.12' => 'Například: 123.34.56.78, 168.111.192.12',
'Group' => 'Skupina',
'Inactive' => 'Neaktivní',
'Language' => 'Jazyk',
'Login' => 'Přihlášení',
'Name' => 'Jméno',
'OS' => 'Operační systém',
'Password' => 'Heslo',
'Password has been changed' => 'Heslo bylo změněno',
'Permission creation' => 'Vytvoření oprávnění',
'Permission groups' => 'Skupiny oprávnění',
'Permissions' => 'Oprávnění',
'Permissions for role - "{role}"' => 'Oprávnění pro roli - "{role}"',
'Permissions for role:' => 'Oprávnění pro roli: ',
'Registration IP' => 'Registrační IP',
'Repeat password' => 'Zopakovat heslo',
'Reset' => 'Resetovat',
'Role creation' => 'Vytvoření role',
'Roles' => 'Role',
'Roles and permissions' => 'Role a oprávnění',
'Roles and permissions for user:' => 'Role a oprávnění pro uživatele:',
'Rule' => 'Pravidlo',
'Save' => 'Uložit',
'Saved' => 'Uloženo',
'Search' => 'Hledat',
'Settings for permission' => 'Nastavení pro oprávnění',
'Status' => 'Stav',
'Superadmin' => 'Superadministrátor',
'Too many attempts' => 'Příliš mnoho pokusů',
'Type' => 'Typ',
'Updated' => 'Aktualizováno',
'User' => 'Uživatel',
'User agent' => 'Uživatelský agent',
'User creation' => 'Vytvoření uživatele',
'Users' => 'Uživatelé',
'Visit Time' => 'Čas návštěvy',
'Visit log' => 'Log návštěv',
'Wrong format. Enter valid IPs separated by comma' => 'Špatný formát. Zadejte platné IP adresy oddělené čárkou',
'Wrong password' => 'Špatné heslo',
'You can not change own permissions' => 'Nemůžete změnit vlastní oprávnění',
'Refresh routes (and delete unused)' => 'Obnovit trasy (a smazat nepoužité)',
'Refresh routes' => 'Obnovit trasy',
'Search route' => 'Hledat trasu',
'Show only selected' => 'Zobrazit pouze vybrané',
'Show all' => 'Zobrazit vše',
];
