<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
'Authorization' => 'Autorizace',
'Call your administrator' => 'Obraťte se na svého správce',
'Captcha' => 'Ověřovací kód',
'Check your E-mail for further instructions' => 'Zkontrolujte svůj e-mail pro další instrukce',
'Check your e-mail {email} for instructions to activate account' => 'Zkontrolujte svůj e-mail {email} pro instrukce k aktivaci účtu. V případě potřeby zkontrolujte i složku se spamem. Máte 24 hodin na aktivaci. Pokud jste do několika hodin neobdrželi aktivační e-mail, prosím, kontaktujte nás na e-mailu uvedeném při registraci.',
'Confirm' => 'Potvrdit',
'Confirm E-mail' => 'Potvrzení e-mailu',
'Continue' => 'Pokračovat',
'Could not send confirmation email' => 'Nepodařilo se odeslat potvrzovací e-mail na uvedenou adresu',
'Download the user manual in pdf' => 'Stáhněte si uživatelskou příručku ve formátu PDF',
'E-mail confirmation for' => 'E-mailové potvrzení pro',
'E-mail confirmed' => 'E-mail potvrzen',
'E-mail is invalid' => 'E-mail je neplatný',
'First steps for beginners' => 'První kroky pro začátečníky',
'Forgot password ?' => 'Zapomenuté heslo?',
'Forgot username ?' => 'Zapomenuté uživatelské jméno?',
'Incorrect username or password.' => 'Nesprávné uživatelské jméno nebo heslo.',
'Login' => 'Přihlášení',
'Login has been taken' => 'Uživatelské jméno je již obsazené',
'Username' => 'Uživatelské jméno',
'Password' => 'Heslo',
'Repeat password' => 'Opakování hesla',
'Password recovery' => 'Obnova hesla',
'Password reset for' => 'Reset hesla pro',
'Quick help' => 'Rychlá pomoc',
'Recover' => 'Obnovit',
'Register' => 'Registrace',
'Registration' => 'Registrace',
'Registration - confirm your e-mail' => 'Registrace - potvrďte svůj e-mail',
'Remember me' => 'Zapamatuj si mě',
'Repeat password' => 'Opakujte heslo',
'This E-mail already exists' => 'Tento e-mail již v systému existuje',
'Token not found. It may be expired' => 'Token nebyl nalezen. Mohl vypršet',
'Token not found. It may be expired. Try reset password once more' => 'Token nebyl nalezen. Mohl vypršet. Zkuste znovu resetovat heslo',
'Too many attempts' => 'Příliš mnoho pokusů',
'Unable to send message for email provided' => 'Nepodařilo se odeslat zprávu na poskytnutý e-mail',
'User' => 'Uživatel',
'You could not login from this IP' => 'Z tohoto IP se nemůžete přihlásit',
];
