<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Authorization' => 'Bejelentkezés',
	'Call your administrator' => 'Forduljon az adminisztrátorához',
    'Captcha' => 'Ellenörző kód',
    'Check your E-mail for further instructions' => 'Ellenőrizd a postafiókodat a további teendőkért',
    'Check your e-mail {email} for instructions to activate account' => 'Ellenőrizd a {email} postafiókodat a további teendőkért. Szükség esetén ellenőrizd a spam mappa tartalmát is. 
    Az aktiválásra 24 óra áll rendelkezésedre. Ha nem kaptad meg az aktiváló levelet néhány órán belül, akkor jelezd a regisztrációnál megadott e-mail címről az elérhetőségeink valamelyikén.',
    'Confirm' => 'Aktivál',
    'Confirm E-mail' => 'Aktiváló E-mail',
    'Continue' => 'Tovább',
    'Could not send confirmation email' => 'Az aktiváló e-mail nem volt elküldhető a megadott címre',
	'Download the user manual in pdf' => 'Töltse le pdf útmutatónkat',
    'E-mail confirmation for' => 'Aktiváló e-mail',
    'E-mail confirmed' => 'E-mail aktiválva',
    'E-mail is invalid' => 'A megadott e-mail cím érvénytelen',
	'First steps for beginners' => 'Hogyan kezdjük használni az oldalt?',
    'Forgot password ?' => 'Elfelejtett jelszó',
	'Forgot username ?' => 'Elfelejtett felhasználónév',
    'Incorrect username or password.' => 'Rossz felhasználó nevet vagy jelszót adott meg.',
    'Login' => 'Bejelentkezés',
    'Login has been taken' => 'A felhasználónév foglalt',
    'Username' => 'Felhasználónév',
    'Password' => 'Jelszó',
	'Repeat password' => 'Jelszó ismétlése',
    'Password recovery' => 'Jelszó visszaállítás',
    'Password reset for' => 'Jelszó visszaállítás',
	'Quick help' => 'GYORS SEGÍTSÉG',
    'Recover' => 'Visszaállít',
    'Register' => 'Regisztrálás',
    'Registration' => 'Regisztráció',
    'Registration - confirm your e-mail' => 'Regisztráció megerősítése',
    'Remember me' => 'Emlékezz rám',
    'Repeat password' => 'Jelszó még egyszer',
    'This E-mail already exists' => 'Ez az e-mail cím már létezik a rendszerben',
    'Token not found. It may be expired' => 'A regisztráció aktiválási ideje sajnos lejárt',
    'Token not found. It may be expired. Try reset password once more' => 'Az aktiválási idő sajnos lejárt. Próbálja ismét a jelszó visszaállítást',
    'Too many attempts' => 'Túl sok próbálkozás',
    'Unable to send message for email provided' => 'A megadott e-mail címre nem lehetett üzenetet küldeni',
	'User' => 'Felhasználó',
    'You could not login from this IP' => 'Ön nem léphet be erről az IP címről',
];
