<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'Azonosító',
    'Username' => 'Felhasználónév',
    'Active' => 'Aktív',
    'Are you sure you want to delete this user?' => 'Biztos vagy benne, hogy törlöd ezt a felhasználót?',
    'Banned' => 'Tiltott',
    'Bind to IP' => 'IP-re korlátoz',
    'Browser' => 'Böngésző',
    'Change own password' => 'Jelszó módosítása',
    'Change password' => 'Jelszó módosítása',
    'Changing password' => 'Jelszó módosítása',
    'Changing password for user: ' => 'Jelszó módosítása ennél a felhasználónál: ',
    'Child permissions' => 'Gyermek jogosultságok',
    'Child roles' => 'Gyermek szerepkörök',
    'Code' => 'Kód',
    'Create' => 'Létrehoz',
    'Created' => 'Létrehozva',
    'Creating permission group' => 'Jogosultság csoport létrehozása',
    'Current password' => 'Jelenlegi jelszó',
    'Data' => 'Adat',
    'Delete' => 'Törlés',
    'Description' => 'Leírás',
    'E-mail confirmed' => 'E-mail megerősítve',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => '',
    'Edit' => 'Módosítás',
    'Editing' => 'Módosítás',
    'Editing permission group' => 'Jogosultság csoport módosítása',
    'Editing permission: ' => 'Jogosultság módosítása: ',
    'Editing role: ' => 'Szerepkör módosítása: ',
    'Editing user: ' => 'Felhasználó módosítása: ',
    'For example: 123.34.56.78, 168.111.192.12' => 'Például: 123.34.56.78, 168.111.192.12',
    'Group' => 'Csoport',
    'Inactive' => 'Inaktív',
    'Language' => 'Nyelv',
    'Login' => 'Bejelentkezés',
    'Name' => 'Név',
    'OS' => 'Operácios rendszer',
    'Password' => 'Jelszó',
    'Password has been changed' => 'A jelszó módosítva',
    'Permission creation' => 'Jogosultság létrehozása',
    'Permission groups' => 'Jogosultság csoportok',
    'Permissions' => 'Jogosultságok',
    'Permissions for role - "{role}"' => 'Jogosultságok a "{role}" szerepkörnek',
    'Permissions for role:' => 'Jogosultságok a szerepkörnek: ',
    'Registration IP' => 'Regisztrációs IP',
    'Repeat password' => 'Jelszó mégegyszer',
    'Reset' => 'Visszaállítás',
    'Role creation' => 'Szerepkör létrehozása',
    'Roles' => 'Szerepkörök',
    'Roles and permissions' => 'Szerepkörök és jogosultságok',
    'Roles and permissions for user:' => 'Szerepkörök és jogosultságok neki:',
    'Rule' => 'Szabály',
    'Save' => 'Mentés',
    'Saved' => 'Sikeres mentés',
    'Search' => 'Keresés',
    'Settings for permission' => 'A jogosultság beállításai',
    'Status' => 'Állapot',
    'Superadmin' => '',
    'Too many attempts' => 'Túl sok próbákozás',
    'Type' => 'Típus',
    'Updated' => 'Frissítve',
    'User' => 'Felhasználó',
    'User agent' => '',
    'User creation' => 'Felhasználó létrehozása',
    'Users' => 'Felhasználók',
    'Visit Time' => 'Látogatás ideje',
    'Visit log' => 'Látogatások',
    'Wrong format. Enter valid IPs separated by comma' => 'Rossz formátum. Az IP-címeket vesszővel elválasztva írd be',
    'Wrong password' => 'Hibás jelszó',
    'You can not change own permissions' => 'Nem állíthatod át a saját jogosultságaidat',
    'Refresh routes (and delete unused)' => 'Útvonalak frissítése (és a nem használtak törlése)',
    'Refresh routes' => 'Útvonalak frissítése',
    'Search route' => 'Útvonal keresése',
    'Show only selected' => 'Kiválasztottak mutatása',
    'Show all' => 'Mind mutatása'
];
