<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
'ID' => 'Identificator',
'Username' => 'Nume de utilizator',
'Active' => 'Activ',
'Are you sure you want to delete this user?' => 'Ești sigur că vrei să ștergi acest utilizator?',
'Banned' => 'Blocat',
'Bind to IP' => 'Legat de IP',
'Browser' => 'Browser',
'Change own password' => 'Schimbă propria parolă',
'Change password' => 'Schimbă parola',
'Changing password' => 'Schimbarea parolei',
'Changing password for user: ' => 'Schimbarea parolei pentru utilizator: ',
'Child permissions' => 'Permisiuni secundare',
'Child roles' => 'Roluri secundare',
'Code' => 'Cod',
'Create' => 'Crează',
'Created' => 'Creat',
'Creating permission group' => 'Crearea unui grup de permisiuni',
'Current password' => 'Parola actuală',
'Data' => 'Date',
'Delete' => 'Șterge',
'Description' => 'Descriere',
'E-mail confirmed' => 'E-mail confirmat',
'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => 'Un e-mail cu link de activare a fost trimis la <b>{email}</b>. Acest link va expira în {minutes} min.',
'Edit' => 'Editează',
'Editing' => 'Editare',
'Editing permission group' => 'Editarea unui grup de permisiuni',
'Editing permission: ' => 'Editarea permisiunii: ',
'Editing role: ' => 'Editarea rolului: ',
'Editing user: ' => 'Editarea utilizatorului: ',
'For example: 123.34.56.78, 168.111.192.12' => 'De exemplu: 123.34.56.78, 168.111.192.12',
'Group' => 'Grup',
'Inactive' => 'Inactiv',
'Language' => 'Limbă',
'Login' => 'Autentificare',
'Name' => 'Nume',
'OS' => 'Sistem de operare',
'Password' => 'Parolă',
'Password has been changed' => 'Parola a fost schimbată',
'Permission creation' => 'Crearea permisiunii',
'Permission groups' => 'Grupuri de permisiuni',
'Permissions' => 'Permisiuni',
'Permissions for role - "{role}"' => 'Permisiuni pentru rolul - "{role}"',
'Permissions for role:' => 'Permisiuni pentru rolul: ',
'Registration IP' => 'IP de înregistrare',
'Repeat password' => 'Repetă parola',
'Reset' => 'Resetare',
'Role creation' => 'Crearea unui rol',
'Roles' => 'Roluri',
'Roles and permissions' => 'Roluri și permisiuni',
'Roles and permissions for user:' => 'Roluri și permisiuni pentru utilizator:',
'Rule' => 'Regulă',
'Save' => 'Salvează',
'Saved' => 'Salvat',
'Search' => 'Caută',
'Settings for permission' => 'Setări pentru permisiune',
'Status' => 'Stare',
'Superadmin' => 'Superadmin',
'Too many attempts' => 'Prea multe încercări',
'Type' => 'Tip',
'Updated' => 'Actualizat',
'User' => 'Utilizator',
'User agent' => 'Agent utilizator',
'User creation' => 'Crearea utilizatorului',
'Users' => 'Utilizatori',
'Visit Time' => 'Timp de vizită',
'Visit log' => 'Jurnal de vizite',
'Wrong format. Enter valid IPs separated by comma' => 'Format greșit. Introduceți IP-uri valide separate prin virgulă',
'Wrong password' => 'Parolă greșită',
'You can not change own permissions' => 'Nu poți schimba propriile permisiuni',
'Refresh routes (and delete unused)' => 'Reîmprospătare rute (și ștergerea celor neutilizate)',
'Refresh routes' => 'Reîmprospătare rute',
'Search route' => 'Caută rută',
'Show only selected' => 'Afișează doar cele selectate',
'Show all' => 'Afișează tot',
];
