<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
'Authorization' => 'Autorizare',
'Call your administrator' => 'Contactați administratorul',
'Captcha' => 'Cod de verificare',
'Check your E-mail for further instructions' => 'Verificați-vă e-mailul pentru instrucțiuni suplimentare',
'Check your e-mail {email} for instructions to activate account' => 'Verificați e-mailul {email} pentru instrucțiuni de activare a contului. Verificați și folderul de spam dacă este necesar. Aveți 24 de ore la dispoziție pentru activare. Dacă nu primiți e-mailul de activare în câteva ore, vă rugăm să ne contactați folosind adresa de e-mail furnizată la înregistrare.',
'Confirm' => 'Confirmă',
'Confirm E-mail' => 'Confirmare e-mail',
'Continue' => 'Continuă',
'Could not send confirmation email' => 'E-mailul de confirmare nu a putut fi trimis',
'Download the user manual in pdf' => 'Descărcați manualul utilizatorului în format PDF',
'E-mail confirmation for' => 'Confirmare e-mail pentru',
'E-mail confirmed' => 'E-mail confirmat',
'E-mail is invalid' => 'E-mailul este invalid',
'First steps for beginners' => 'Primii pași pentru începători',
'Forgot password ?' => 'Ați uitat parola?',
'Forgot username ?' => 'Ați uitat numele de utilizator?',
'Incorrect username or password.' => 'Nume de utilizator sau parolă incorectă.',
'Login' => 'Autentificare',
'Login has been taken' => 'Numele de utilizator este deja luat',
'Username' => 'Nume de utilizator',
'Password' => 'Parolă',
'Repeat password' => 'Repetare parolă',
'Password recovery' => 'Recuperare parolă',
'Password reset for' => 'Resetare parolă pentru',
'Quick help' => 'Ajutor rapid',
'Recover' => 'Recuperează',
'Register' => 'Înregistrare',
'Registration' => 'Înregistrare',
'Registration - confirm your e-mail' => 'Înregistrare - confirmați e-mailul',
'Remember me' => 'Ține-mă minte',
'Repeat password' => 'Repetă parola',
'This E-mail already exists' => 'Acest e-mail există deja în sistem',
'Token not found. It may be expired' => 'Tokenul nu a fost găsit. Este posibil să fi expirat',
'Token not found. It may be expired. Try reset password once more' => 'Tokenul nu a fost găsit. Este posibil să fi expirat. Încercați din nou resetarea parolei',
'Too many attempts' => 'Prea multe încercări',
'Unable to send message for email provided' => 'Nu se poate trimite mesajul la e-mailul furnizat',
'User' => 'Utilizator',
'You could not login from this IP' => 'Nu vă puteți autentifica de pe acest IP',
];
